name: lua cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: libreadline
      run: sudo apt-get install libreadline-dev
    - name: make linux
      run: make linux
