name: lua cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation depends
      run: |
        sudo apt-get install libreadline-dev zip
    - name: make linux
      run: make linux
    - name: copy files
      run: mkdir -p release/linux && cp src/lua release/linux/ && cp src/luac release/linux/
    - name: archive files
      run: zip -r release/linux.zip release/linux
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: lua
        path: release/linux.zip
