name: lua cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installation depends
      run: |
        sudo apt-get install libreadline-dev
    - name: make linux
      run: make linux
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: lua
        path: |
          src/lua
          src/luac
