name: lua cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation depends
      run: |
        sudo apt-get install libreadline-dev zip
    - name: make linux
      run: make linux
    - name: copy files
      run: mkdir -p release/linux && cp src/lua release/linux/ && cp src/luac release/linux/
    - name: archive files
      run: cd release && tar cvf linux.tar linux
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: lua-linux.tar
        path: release/linux.tar
  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation depends
      run: ls -al
    - name: make macosx
      run: make macosx
    - name: copy files
      run: mkdir -p release/osx && cp src/lua release/osx/ && cp src/luac release/osx/
    - name: archive files
      run: cd release && tar cvf osx.tar osx
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: lua-osx.tar
        path: release/osx.tar
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: make generic
      run: make generic
    - name: copy files
      run: mkdir -p release/win && cp src/lua.exe release/win/ && cp src/luac.exe release/win/
    - name: archive files
      run: cd release && tar cvf win.tar win
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: lua-win.tar
        path: release/win.tar
